server:
  port: 6501

spring:
  application:
    name: fxz-mall-xxl-job
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:fxz-nacos}:8848
      config:
        server-addr: ${NACOS_HOST:fxz-nacos}:8848
  config:
    import:
      - optional:nacos:fxz-application-common.yaml
  redis:
    database: 0
    host: fxz-redis
    port: 6379
    password: fxzcloud-redis
    lettuce:
      pool:
        # 最大连接
        min-idle: 8
        # 最大空闲连接
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000

fxz:
  common:
    xxl-job:
      appname: ${spring.application.name}
      admin-addresses: http://127.0.0.1:9003/xxl-job-admin
      port: 9900
