server:
  port: 6501

spring:
  application:
    name: fxz-mall-xxl-job
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:fxz-nacos}:8848
      config:
        server-addr: ${NACOS_HOST:fxz-nacos}:8848
  config:
    import:
      - optional:nacos:fxz-application-common.yaml

